---
title: "Lab 3"
author: "Adaeze Obinelo"
format:
  html:
    embed-resources: true
---

# Step 1+2\--\> read the data

There are 2377343 data points and 30 variables

```{r}
#| echo: false
2 * 2
met <- data.table::fread(file.path("~", "Downloads", "met_all.gz")) 
dim(met)
head(met)
tail(met)
str(met)
summary(met[,8:13])
table(met$year)
table(met$hour)
table(met$month)
summary(met$lat)
summary(met$lon)
summary(met$temp)
summary(met$elev)
summary(met$wind.sp)
met[met$elev==9999.0] <- NA
summary(met$elev)
# this ^ gives us statistic summary of temp variabl


```

## Step 3

```{r}
#| echo: false
2 * 2
str(met)
```

## Step 4

```{r}
#| echo: false
2 * 2
summary(met[,8:13])
table(met$year)
table(met$hour)
table(met$month)
summary(met$lat)
summary(met$lon)
summary(met$temp)
summary(met$elev)
summary(met$wind.sp)
met[met$elev==9999.0] <- NA
summary(met$elev)
elev <- met[elev==max(elev), ]
summary(elev)
```

## Step 5

```{r}
#| echo: false
2 * 2

mean(is.na(met$temp))
#tell us whether or not a particular value is NA i.e. about 2.5% of temperature values are missing

met_ss <- met[met$temp == -40.00, c('hour', 'lat', 'lon', 'elev', 'wind.sp')]
# creates new dataset called 'met_ss' use square brackets to subset, c means create a vector (pulls out columns) of specified variables 
dim(met_ss)
summary(met_ss)

# we think -40 observations are probably not real, so we want to get rid of them
# will subset again to make new set without them
# will call it 'met' to override original met dataset

met <- met[met$temp != -40.00,]
# double equal sign means 'equals' != means 'not equal to

dim(met)
summary(met)
#look at new dataset met

# if you do met temp procedure in console first, you'll get an idea of how things will be ordered--> itll give u integers
met <- met[order(met$temp)]
summary(met$temp)
summary(met)

head(met)
tail(met)
head(met)[,c(1,8:10,24)]
tail(met)[,c(1,8:10,24)]
# the c makes a vector again --> we are only pulling these variables; see str func to find out which variables r which

met_daily <- met[, .(
  temp = mean(temp),
  lat  = mean(lat),
  lon  = mean(lon),
  elev = mean(elev)
), by = c("USAFID", "day")][order(temp)]
head(met_daily)

tail(met_daily)

library(magrittr)
library(dplyr)
met_daily_dplyr <- met %>% 
  group_by(USAFID, day) %>%
  summarize(temp = mean(temp)) %>%
  arrange(desc(temp))

# use %>% to "pipe"--> express a string of multiple operations; need magrittr package to use this version of pipe
# that's why i put that in first
# also need dplyr function to use arrange lol so i added that next

summary(met_daily_dplyr)

head(met_daily_dplyr)
tail(met_daily_dplyr)

```

## Step 6

```{r}
#| echo: false
2 * 2
elev <- met[elev==max(elev), ]
summary(elev)
```

## Step 7

```{r}
#| echo: false
2 * 2
hist(met$temp, col = "pink")
boxplot(met$temp, col = "pink")
#library('devtools')
#install_version('knitr' , version='1.42')
# first, need to make dataset of unique lon and lats, call it met stations
met_stations <- (unique(met[,c("lat","lon")]))  
dim(met_stations)
#unique variables for lat and long^

#use leaflet function
library(leaflet)

leaflet(met_stations) %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addCircles(lat = ~lat, lng = ~lon, opacity = 1, fillOpacity = 1, radius = 400)

#marking the maximum and min temperature with diff colors to a new map
min <- met_daily[1] # first observation
max <- met_daily[.N] #.N denotes the last observation

leaflet() %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addCircles(
    data = min,
    lat = ~lat, lng = ~lon, popup = "Min temp.",
    opacity = 1, fillOpacity = 1, radius = 400, color = "blue"
  ) %>%
  addCircles(
    data = max,
    lat = ~lat, lng = ~lon, popup = "Max temp.",
    opacity=1, fillOpacity=1, radius = 400, color = "red"
  )

```

```{r}
plot(met_daily$lat, met_daily$temp, pch=19, cex=0.5)
# plot met daily lat x, against y of temp variable
# pch denotes the fill of the dot, default is one, which is just outline of circye
# cex gives the size, can make bigger or smaller points by adjusting this; 1 is baseline)

# can add simple linear regression using lm function
mod <- lm(temp ~ lat, data = met_daily)
#making new data mod', from met daily data; format 'x' ~ 'y' --> model x variable based on y variable
# for us, this is temp by x
# can type in mod in console at the bottom to see the form of this line + coefficients

abline(mod, col = "orange", lwd = 2)

# abline func makes a line, needs slope and intercept
# when we ggive it the mod data, it can find the slope and intercept itself
# lwd = line width



```

```{r}
#| echo: false
2 * 2
elev <- met[elev==max(elev), ]
summary(elev)

leaflet(elev) %>%
  addProviderTiles('OpenStreetMap') %>% 
  addCircles(lat=~lat,lng=~lon, opacity=1, fillOpacity=1, radius=100)

```

```{r}
#| echo: false
2 * 2
library(lubridate)
elev$date <- with(elev, ymd_h(paste(year, month, day, hour, sep= ' ')))
summary(elev$date)

elev <- elev[order(date)]
head(elev)

plot(elev$date, elev$temp, type='l')

plot(elev$date, elev$wind.sp, type='l')
```

## Step 8

1\. Who are the contributors on this dataset? I.e. can anyone contribute, or was data collected by research team


2\. what was the purpose of this dataset?

```{}
```
